name: Reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifect files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Locate file
        run: ls
      - name: output information
        run: echo "Deploying and uploading"
